system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: 'O0'
  seed: 42
  val_while_train: True
  drop_overflow_update: False

common:
  character_dict_path: &character_dict_path  #mindocr/utils/dict/en_dict.txt
  num_classes: &num_classes 37 # num_chars_in_dict+1,  TODO: retreive it from dict or check correctness
  max_text_len: &max_text_len 24
  infer_mode: &infer_mode False
  use_space_char: &use_space_char False
  batch_size: &batch_size 256
  
model:
  type: rec
  transform:
    name: STN_ON
    tps_inputsize: [32,64]
    tps_outputsize: [32,100]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  backbone:
    name: SVTRNet
    img_size: [32,100]
    out_char_num: 25 # W//4 or W//8 or W/12
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [64,128,256]
    depth: [3,6,3]
    num_heads: [2,4,8]
    mixer: ['Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: False
  neck:
    name: Im2Seq
  head:
    name: CTCHead
    weight_init: crnn_customised
    bias_init: crnn_customised
    out_channels: *num_classes
postprocess:
  name: RecCTCLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char
metric:
  name: RecMetric
  main_indicator: acc
  character_dict_path: *character_dict_path
  ignore_space: True
  print_flag: False

loss:
  name: CTCLoss 
  pred_seq_len: 25 # TODO: retrieve from the network output shape.
  max_label_len: *max_text_len  # this value should be smaller than pre_seq_len
  batch_size: *batch_size

scheduler: 
  scheduler: warmup_cosine_decay
  min_lr: 0.0000001
  lr: 0.01
  num_epochs: 35
  warmup_epochs: 1
  decay_epochs: 34
  
optimizer:
  opt: adamw
  filter_bias_and_bn: False
  momentum: 0.9
  weight_decay: 0.05
  nesterov: False
  beta1: 0.9
  beta2: 0.99
  no_weight_decay_params: ['beta', 'gamma', 'pos_emb', 'bias'] # filter norm and bias params from weight decay
  grouping_strategy: 'svtr'

loss_scaler:
  type: static
  loss_scale: 512.0
  
train:
  ckpt_save_dir: /home/mindspore/lby_spencer/mindocr/mindocr/output/rec/0414version
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    data_dir: /home/mindspore/lby_spencer/svtr_dataset/training
    # label_files: /data/ocr_datasets/ic15/word_recognition/rec_gt_train.txt
    sample_ratio: 1.0
    shuffle: True
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - SVTRRecAug:
          aug_type: 0
      - RecCTCLabelEncode:
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          lower: True
      - RecResizeImg: # different from paddle (paddle converts image from HWC to CHW and rescale to [-1, 1] after resize.
          image_shape: [64,256]
          infer_mode: *infer_mode
          character_dict_path: *character_dict_path
          padding: False
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
          bgr_to_rgb: True
          is_hwc: True
          mean : [127.0, 127.0, 127.0]
          std : [127.0, 127.0, 127.0]
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'text_seq'] #, 'length'] #'img_path'] 
    num_columns_to_net: 1 # num inputs for network forward func in output_keys
    #keys_for_loss: 4 # num labels for loss func

  loader:
      shuffle: True # TODO: tbc
      batch_size: *batch_size
      drop_remainder: True
      max_rowsize: 12
      num_workers: 4

eval:
  # ckpt_load_path: /home/mindocr/lby_spencer/mindocr/mindocr/output/rec/2203version/best.ckpt
  dataset_sink_mode: False
  dataset:
    type: LMDBDataset
    data_dir: /home/mindspore/lby_spencer/svtr_dataset/evaluation
    # label_files: /data/ocr_datasets/ic15/word_recognition/rec_gt_train.txt
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          img_mode: BGR
          to_float32: False
      - RecCTCLabelEncode:
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          lower: True
      - RecResizeImg: # different from paddle (paddle converts image from HWC to CHW and rescale to [-1, 1] after resize.
          image_shape: [64,256]
          infer_mode: *infer_mode
          character_dict_path: *character_dict_path
          padding: False
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
          bgr_to_rgb: True
          is_hwc: True
          mean : [127.0, 127.0, 127.0]
          std : [127.0, 127.0, 127.0]
      - ToCHWImage:
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'text_padded', 'text_length']  # TODO return text string padding w/ fixed length, and a scaler to indicate the length 
    num_columns_to_net: 1 # num inputs for network forward func

  loader:
      shuffle: False # TODO: tbc
      batch_size: 256
      drop_remainder: True
      max_rowsize: 12
      num_workers: 2
